CREATE TABLE DEPT47 (
    DEPTNO NUMBER PRIMARY KEY,
    DNAME VARCHAR2(50),
    LOC VARCHAR2(50)
);

CREATE TABLE EMP47 (
    EMPNO NUMBER PRIMARY KEY,
    ENAME VARCHAR2(50),
    JOB CHAR(20),
    MGR NUMBER,
    HIREDATE DATE,
    SAL NUMBER,
    COMM NUMBER,
    DEPTNO NUMBER,
    CONSTRAINT FK_DEPT FOREIGN KEY (DEPTNO) REFERENCES DEPT47(DEPTNO)
);
